project_id = "ttnlrnmdxkecomdylckl"

[functions.simple-create-driver]
verify_jwt = false

[functions.delete-driver-admin]
verify_jwt = false

[functions.send-driver-credentials]
verify_jwt = false

[functions.send-invoices]
verify_jwt = false

[functions.server-validation]
verify_jwt = false