project_id = "ttnlrnmdxkecomdylckl"

[functions.comprehensive-create-driver]
verify_jwt = false

[functions.delete-driver-comprehensive]
verify_jwt = false

[functions.send-driver-credentials]
verify_jwt = false

[functions.send-invoices]
verify_jwt = false

[functions.server-validation]
verify_jwt = false

[functions.test-driver-creation]
verify_jwt = false

[functions.invite-user]
verify_jwt = true